[package]
name = "backend-micromouse"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tungstenite = "0.28.0"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.28.0"
futures-util = "0.3"
# log = "*"
# env_logger = "*"
tokio-util = "*"
incr_stats = "*"
# log4rs 
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-log = "0.2" # optional= "*"
console = "0"

[features]
comm_stats = []
default = ["comm_stats"]
