[package]
name = "backend-micromouse"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tungstenite = "0.29.0"
tokio = { version = "1", features = ["full", "tracing"] }
tokio-tungstenite = "0.29.0"
futures-util = "0.3"
# log = "*"
# env_logger = "*"
tokio-util = "0.7.18"
incr_stats = "1.0.2"
# log4rs 
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
tracing-log = "0.2"
tracing-appender = "0.2"
console = "0.16.3"
rand = "0.8.6"
serde_json = "1.0.150"
chrono = "0.4.44"
pathdiff = "0.2.3"
ansi-to-html = "0.2.3"
thiserror = "2.0.18"
derive_more = {git = "https://github.com/JelteF/derive_more", branch = "master", features = ["from"]}
macroquad = "0.4.15"
console-subscriber = "0.5.0"

[features]
comm_stats = []
hyperlink_logging = []
term_logging = []
tokio_console = []
default = ["comm_stats", "term_logging", "hyperlink_logging"]
